## YAML Template.
---
services:
  registry-discovery:
    container_name: id-eureka
    image: eureka-image:latest
    ports:
      - 8761:8761
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M 

  admin-discovery:
    container_name: id-spring-admin
    image: spring-admin-image:latest
    ports:
      - 8062:8062
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M 
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery

  product-catalog:
    container_name: bd-product-catalog
    image: products-image:latest
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8083:8083

  transaction-catalog:
    container_name: bd-transaction-catalog
    image: transactions-image:latest
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8082:8082

  apigateway:
    container_name: apigateway-app
    image: api-gateway-image:latest
    environment:
       - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8080:8080

  customer-config-server:
    container_name: config-server-app
    image: config-server-image:latest
    environment:
      - JAVA_OPTS=
        -Xms256M 
        -Xmx256M
        -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
    depends_on:
      - registry-discovery
    ports:
      - 8888:8888
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  customer:
    container_name: customer-app
    image: customer-image:latest
    environment:
      - JAVA_OPTS=
         -Xms256M 
         -Xmx256M
         -DEUREKA_SERVER=http://registry-discovery:8761/eureka/
      - CONFIG_SERVER=http://customer-config-server:8888
      - SPRING_CLOUD_CONFIG_NAME=config-client
      - SPRING_CLOUD_CONFIG_PROFILE=local
    depends_on:
      - registry-discovery
      - postgres_db
      - customer-config-server
    # ports:
      # - 8081:8081

  postgres_db:
    container_name: postgres
    image: postgres:latest
    ports:
        - 5432:5432
    volumes:
        - ./dbfiles:/docker-entrypoint-initdb.d
        - ./postgres_data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty
        POSTGRES_DB: postgres


  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "qwerty"
    ports:
      - 80:80
    depends_on:
      - postgres_db



