server:
  port: 8080

logging:
  level:
    '[org.springframework.cloud.gateway]': DEBUG
    '[reactor.netty.http.client]': DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://host.docker.internal:8761/eureka}

spring:
  application:
    name: infraestructuradomain-api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
      - id: customer_service
        uri: lb://bussinessdomain-customer
        predicates:
        - name: Path
          args:
            pattern: /**
